### ISSUE TITLE
Password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by osaris** [greut/rails-for-all#2]
Woops, running ```install.sh``` and then ```configure.py``` give me ```Password authentication failed for user "postgres"```

**Comment by greut** [comment]
The password is not changed automagically as of yet.

**Comment by osaris** [comment]
Automagically automagically :-) What solution do you recommend to get the script running ? I tried to pass the password through env variable but that doesn't seem to work. However I'm not a pg expert !
